### ISSUE TITLE
Error in running googletrans

### ISSUE THREAD

**Issue by pengyu** [ssut/py-googletrans#89]
I got the following error. Does anybody know what is wrong with it? Thanks.

```
$ python3
Python 3.7.0b4 (v3.7.0b4:eb96c37699, May  2 2018, 04:13:13) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from googletrans import Translator
>>> translator = Translator()
>>> translator.translate('안녕하세요.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by yeungocanh** [comment]
+1 . I get the same error.

**Comment by bmosley** [comment]
+1 same error :(

**Comment by markolofsen** [comment]
Fixed library are here [https://pypi.org/project/py-translator/](https://pypi.org/project/py-translator/)

**Comment by Khallil** [comment]
@markolofsen thanks it's working

**Comment by durakkerem** [comment]
I get the famous `JSONDecodeError: Expecting value` error with the py-translator API although it worked for a certain while. Guessing that it's a rate limit thing, I waited for ~2 hours but I still get the error.

**Comment by markolofsen** [comment]
**pip3 install py_translator==1.7.4**

```
from py_translator import Translator
proxy = {
        'http': 'http://username:password@1.1.1.1:1234',
        'https': 'http://username:password@1.1.1.1:1234',
}
s = Translator(proxies=proxy).translate(text='Hello my friend', dest='es').text
print(s)

```

**Comment by durakkerem** [comment]
@markolofsen, is this a fixed to the Expecting Value error? Can you describe how it works?

**Comment by markolofsen** [comment]
@durakkerem You have to buy good proxies and using each one proxy randomly (like in example above)

**Comment by markolofsen** [comment]
... or pay to Google for each 1 million symbols

**Comment by doobybug** [comment]
this is what I am getting:
ProxyError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffbe8ab2320>: Failed to establish a new connection: [Errno 110] Connection timed out',)))

**Comment by devirstuoso** [comment]
> this is what I am getting:
> ProxyError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffbe8ab2320>: Failed to establish a new connection: [Errno 110] Connection timed out',)))

Same issue
